### ISSUE TITLE
Add shortcut for quering open bug list

### ISSUE THREAD

**Issue by MarkTraceur** [Krinkle/wmbug.com#1]
`/open?product=VisualEditor` would be fantastic, e.g.

Maybe something simple like `/open/extension/MultimediaViewer` as well, and `/open/core`.

Shortcuts like `/closed` and `/easy` and `/critical` with different queries would also be super useful.

**Comment by Krinkle** [comment]
Thanks! Put into an interface like this perhaps?
- `q` -> `buglist.cgi`.<br>Example: [/q?product=VisualEditor&resolution=---](https://bugzilla.wikimedia.org/buglist.cgi?product=VisualEditor&resolution=---)
- `/open/{product}[/{component}]` -> `buglist.cgi?resolution=---`.<br>Example: [/open/MediaWiki](https://bugzilla.wikimedia.org/buglist.cgi?resolution=---&product=MediaWiki), [/open/VisualEditor/ContentEditable](https://bugzilla.wikimedia.org/buglist.cgi?resolution=---&product=VisualEditor&component=ContentEditable), [/open/MediaWiki+extensions/MultimediaViewer](https://bugzilla.wikimedia.org/buglist.cgi?resolution=---&product=MediaWiki%20extensions&component=MultimediaViewer)
- `/open/extension/{component}` -> `buglist.cgi?resolution=---&product=MediaWiki%20extensions`<br>Example: [/open/extension/MultimediaViewer](https://bugzilla.wikimedia.org/buglist.cgi?resolution=---&product=MediaWiki%20extensions&component=MultimediaViewer)

Exactly like you proposed, except for custom queries using `/q`, and having `/open/MediaWiki` instead of  `/open/core` (taking any arbitrary product, with an alias for extension). We can add an alias for "core" as well, of course.

+1 for similar constructs like `/easy` (keyword) and `/critical` (severity). Not sure about `/closed` (status), but I guess could do that as well.

**Comment by Krinkle** [comment]
Pull requests are welcome.

I'd recommend implementation as either plain RewriteRule redirects, or rewriting to e.g. a php script that handles it.
